name: PingPlugin
version: 1.3.9
main: kwangdong.pingplugin.PingPlugin
api-version: 1.21.8
commands:
  ping:
    description: 현재 위치 출력
    usage: /ping cur
  death:
    description: 마지막 사망 위치 출력
    usage: /death <latest|clear>
    aliases: [d]
  wave:
    description: 웨이브 이벤트 처리
    usage: /wave <start|skip|stop>
    aliases: [we]